"""empty message

Revision ID: 406f63074688
Revises: 214a87be52cb
Create Date: 2023-02-06 22:45:49.117843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "406f63074688"
down_revision = "214a87be52cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("article_title", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.drop_column("article_title")

    # ### end Alembic commands ###
