"""empty message

Revision ID: b7a8deed3598
Revises: 406f63074688
Create Date: 2023-02-06 22:50:40.015624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b7a8deed3598"
down_revision = "406f63074688"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.alter_column("article_title", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column(
            "seen_on", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
        )
        batch_op.drop_constraint("history_profile_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "profile", ["profile_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "history_profile_id_fkey", "profile", ["profile_id"], ["id"]
        )
        batch_op.alter_column(
            "seen_on", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
        )
        batch_op.alter_column("article_title", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###
